### ISSUE TITLE
Extraction from tomogram or tilt series has errors

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-emantomo#54]
Hello
I tried **tomo tilt series import -> emantomo tilt series alignment -> emantomo tomogram reconstruction -> emantomo template matching** 
I am trying to use **emantomo - extraction from tilt series**.
I get:
```
00001:   project._getRelationGraph: parent Node is None: 2437
00002:   Traceback (most recent call last):
00003:     File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
00004:       self._run()
00005:     File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
00006:       resultFiles = self._runFunc()
00007:     File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
00008:       return self._func(*self._args)
00009:     File "/shared/scipion3/plugins/scipion-em-emantomo/emantomo/protocols/protocol_tomo_extraction_from_ts.py", line 112, in writeSetOfCoordinates3D
00010:       tltSeries = recoverTSFromObj(coords, self)
00011:     File "/shared/scipion3/plugins/scipion-em-emantomo/emantomo/convert/convert.py", line 837, in recoverTSFromObj
00012:       raise ValueError('Could not find any SetOfTiltSeries associated to %s.' % type(child_obj))
00013:   ValueError: Could not find any SetOfTiltSeries associated to <class 'tomo.objects.SetOfCoordinates3D'>.
00014:   Protocol failed: Could not find any SetOfTiltSeries associated to <class 'tomo.objects.SetOfCoordinates3D'>.

```
I am also not able to do **emantomo - extraction from tomogram.**
I get:
```
00001:   Traceback (most recent call last):
00002:     File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
00003:       self._run()
00004:     File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
00005:       resultFiles = self._runFunc()
00006:     File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
00007:       return self._func(*self._args)
00008:     File "/shared/scipion3/plugins/scipion-em-emantomo/emantomo/protocols/protocol_tomo_extraction_from_tomo.py", line 135, in writeSetOfCoordinates3D
00009:       for tomo in self.getInputTomograms():
00010:   TypeError: 'Float' object is not iterable
00011:   Protocol failed: 'Float' object is not iterable
```
I tried both devel and master.. no change

**Comment by pconesa** [comment]
Thanks! Eman in under strong refactorization. We'll review this too.
